### ISSUE TITLE
Mouselook Navigation Blender Noticeable Lag

### ISSUE THREAD

**Issue by viletuff1** [dairin0d/blender-4.0-scripts#1]
Hi! Not really sure how to use GitHub so sorry if I'm not using this right! I'm using blender 4.0 and the latest Mouse Look Navigation add-on with the Zbrush Preset Loaded. I've noticed since updating to 4.0 there's a slight delay (about .5 seconds) with the response of certain actions. This only happens if I'm panning, orbiting, or using a main sculpting brush ( left mouse button ). After the first lag the rest of the movement is perfectly smooth. I'm unsure what this is caused by, but I've included a video of it. This delay only happens with the add-on enabled, and otherwise my computer runs blender perfectly fine.

I'm using a RTX 2060 super, with an AMD Ryzen 5 3600 and 32 gb of memory.

https://github.com/dairin0d/blender-4.0-scripts/assets/155013135/d28b5d70-7097-4aac-b834-d1a12a11da80

**Comment by dairin0d** [comment]
Hi, just in case: which geometry detection method do you have selected in the addon's preferences?
![image](https://github.com/dairin0d/blender-4.0-scripts/assets/1641842/9025cfe5-9619-490b-afd9-d7068b34460d)

If it's not Z-Buffer, try changing it to Z-Buffer. If it's already Z-Buffer, I'm afraid there's not much that can be done about it (unless Blender developers include additional capabilities in the API).
Due to Blender's quirks, obtaining a depth buffer for geometry detection currently requires to force redraw the entire UI, which can be a somewhat expensive operation. Personally, I don't find the lag noticeable on my laptop, but maybe it's just because I'm testing in simple scene setups and/or my screen resolution is not extremely large.

**Comment by viletuff1** [comment]
Thank you for the response! I am using Z-buffer for geometry detection. I haven't been able to find any solution for this, but I'll continue to try and mess around to see if any settings change this. Thanks!

edit: changing my Screen resolution or window size sadly didn't fix anything either. Using Raycast or selection for geometry detection seems to work good though without any hiccups.
